### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically. Could not resolve angular2-jwt...

### ISSUE THREAD

**Issue by nicolassharp** [auth0/angular2-jwt#294]
`ERROR in Error encountered resolving symbol values statically. Could not resolve angular2-jwt relative to /Users/nicolassharp/Projects/hello/xyz/src/app/app.module.ts., resolving symbol AppModule in /Users/nicolassharp/Projects/hello/xyz/src/app/app.module.ts, resolving symbol AppModule in /Users/nicolassharp/Projects/hello/xyz/src/app/app.module.ts`

And then errors everywhere the module is used. Does anyone have any ideas, this is killllling me!

I should also add:

```
@angular/cli: 1.0.0-beta.32.3
node: 7.6.0
os: darwin x64
@angular/common: 2.4.8
@angular/compiler: 2.4.8
@angular/core: 2.4.8
@angular/forms: 2.4.8
@angular/http: 2.4.8
@angular/platform-browser: 2.4.8
@angular/platform-browser-dynamic: 2.4.8
@angular/router: 3.4.8
@angular/cli: 1.0.0-beta.32.3
@angular/compiler-cli: 2.4.8
```

**Comment by gdelpu** [comment]
This is related to Angular not angular2-jwt. Exporting your service factory function should solve the situation.

`export function authHttpServiceFactory(http: Http, options: RequestOptions) {
    return new AuthHttp(new AuthConfig(), http, options);
}`

Greg

**Comment by nicolassharp** [comment]
@gdelpu thanks for your response. I'm already doing this: 

```
import { AuthHttp, AuthConfig} from 'angular2-jwt';
export function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp( new AuthConfig({}), http, options);
}
```

And get this error:

`ERROR in Error encountered resolving symbol values statically. Could not resolve angular2-jwt relative to /Users/nicolassharp/Projects/hello/src/app/app.module.ts., resolving symbol AppModule in /Users/nicolassharp/Projects/hello/src/app/app.module.ts, resolving symbol AppModule in /Users/nicolassharp/Projects/hello/src/app/app.module.ts`

Has anyone managed to solve this issue?

**Comment by sebhildebrandt** [comment]
Had also kind of the same issue ...

```
ERROR in Error encountered resolving symbol values statically. Reference to a non-exported function (position 5:10 in the original .ts file), resolving symbol AuthModule in [path]/app/services/auth.module.ts
```

I created the auth.module.ty same as in the README. So I changed it - like @gdelpu suggested. This `export`  for function `function authHttpServiceFactory` solved my problem.

**Comment by nicolassharp** [comment]
@sebhildebrandt @gdelpu how do I then use it in services? Presumable doing `import { AuthHttp} from 'angular2-jwt';` is the issue?

**Comment by gdelpu** [comment]
As described in the readme, the only difference is to export the factory function

**Comment by sebhildebrandt** [comment]
As @gdelpu said, the clue is the `export` for the `function authHttpServiceFactory` ...

So my auth.module.ts looks like:

```
import { NgModule } from '@angular/core';
import { Http, RequestOptions } from '@angular/http';
import { AuthHttp, AuthConfig } from 'angular2-jwt';

export function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig(), http, options);
}

@NgModule({
  providers: [
    {
      provide: AuthHttp,
      useFactory: authHttpServiceFactory,
      deps: [Http, RequestOptions]
    }
  ]
})
export class AuthModule {}
```

Then I only need to import this module in e.g. the app.module.ts like:

```
@NgModule({
  declarations: [
    AppComponent,
    ...
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    ...
    AuthModule
  ],
  providers: [
    ...
  ],
  bootstrap: [AppComponent]
})
```

**Comment by nicolassharp** [comment]
@gdelpu unfortunately that's not working for me... I'm already do this in app.module.ts as per the README:

```
import { AuthHttp, AuthConfig } from 'angular2-jwt';
export function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp( new AuthConfig({}), http, options);
}

@NgModule({
    ...
    providers: [
        {
          provide: AuthHttp,
          useFactory: authHttpServiceFactory,
          deps: [ Http, RequestOptions ]
        }
    ]
})
```

I'm really at a lose! Is there any more info I can provide to help debug this? 

The error appears when I run `ng build`:

ERROR in Error encountered resolving symbol values statically. Reference to a non-exported function (position 21:10 in the original .ts file), resolving symbol AppModule in /Users/nicolassharp/Projects/hello/fundstack-web-client/src/app/app.module.ts

```
ERROR in /Users/nicolassharp/Projects/hello/fundstack-web-client/src/app/app.module.ts (20,38): Cannot find module 'angular2-jwt'.)

ERROR in /Users/nicolassharp/Projects/hello/fundstack-web-client/src/app/services/company.service.ts (3,25): Cannot find module 'angular2-jwt'.)

ERROR in /Users/nicolassharp/Projects/hello/fundstack-web-client/src/app/services/person.service.ts (3,25): Cannot find module 'angular2-jwt'.)

ERROR in /Users/nicolassharp/Projects/hello/fundstack-web-client/src/app/services/status_type.service.ts (3,26): Cannot find module 'angular2-jwt'.)

ERROR in /Users/nicolassharp/Projects/hello/fundstack-web-client/src/app/services/tag.service.ts (3,26): Cannot find module 'angular2-jwt'.)

ERROR in /Users/nicolassharp/Projects/hello/fundstack-web-client/src/app/services/task.service.ts (3,26): Cannot find module 'angular2-jwt'.)

ERROR in /Users/nicolassharp/Projects/hello/fundstack-web-client/src/app/services/user.service.ts (3,26): Cannot find module 'angular2-jwt'.)

ERROR in /Users/nicolassharp/Projects/hello/fundstack-web-client/src/app/services/comment.service.ts (3,25): Cannot find module 'angular2-jwt'.)

ERROR in /Users/nicolassharp/Projects/hello/fundstack-web-client/src/app/services/auth.service.ts (2,33): Cannot find module 'angular2-jwt'.)
```

**Comment by sebhildebrandt** [comment]
One more thing:
In the module, that then IMPORTS the auth.module.ts (in my case app.module.ts):

Be sure that you are importing the correct reference: 
```
import {AuthModule} from "./services/auth.module";
```
(and **not** from **angular2-jwt**)

**Comment by nicolassharp** [comment]
@sebhildebrandt in that case how do I use `AuthHttp` to make http call with a JWT? Thanks for your help, I'm sure I'm missing something super obvious, it's driving me crazy!

**Comment by sebhildebrandt** [comment]
Here some quick and dirty code for that (untested):

This is the service, where I use `AuthHttp`: lets call it `books.service.ts`

```
import {Injectable} from '@angular/core';
import {Headers, Response, Headers, RequestOptions} from "@angular/http";
import {AuthHttp} from "angular2-jwt";

import 'rxjs/add/operator/map';

@Injectable()
export class BooksService {

  constructor(private authHttp: AuthHttp) {
  }

  getBooks() {

    data: any;

    // set RequestOptions
    let reqopt: RequestOptions;
    let headers = new Headers();
    headers.append('Accept', 'application/json');
    reqopt = new RequestOptions({
      headers: headers
    });

    // gets data / returns an objervable
    return this.authHttp
      .get('/api/v1/books', reqopt)
      .map(res => {
          this.data = JSON.stringify(data.json());
          console.log(data.json());
      })
      .catch(err => this.handleError(err));
  }
}
```

and this is the consuming component:

```
import {Component, OnInit, OnDestroy, AfterViewInit, ViewChildren} from '@angular/core';

import {Subscription} from "rxjs/Rx";
import {BooksService} from "./services/books.service";
import {subscribeOn} from "rxjs/operator/subscribeOn";

export class BooksComponent implements OnInit, OnDestroy {

  books: any;
  subscription: Subscription;

  constructor(private booksService: BooksService) {
  	this.books = [];
  }

  getBooks() {
    this.subscription = this.booksService
      .getBooks()
      .subscribe(
        books => {
          this.books = books;
        },
        error => {
        	...
        }
      )
  }

  ngOnDestroy() {
    // prevent memory leak by unsubscribing
    this.subscription.unsubscribe();
  }

}  
```

AuthHttp ensures that the service only fires, if you already received and stored a valid token (and the token is not expired). On the server side, you of course need to check the token one more time ;-)

Hope that helps ...

**Comment by nicolassharp** [comment]
@sebhildebrandt OK we're getting there. I had all my services set up as you do...

**auth.module.ts**

```
import { NgModule } from '@angular/core';
import { Http, RequestOptions } from '@angular/http';
import { AuthHttp, AuthConfig } from 'angular2-jwt';

function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp(new AuthConfig(), http, options);
}

@NgModule({
  providers: [
    {
      provide: AuthHttp,
      useFactory: authHttpServiceFactory,
      deps: [Http, RequestOptions]
    }
  ]
})
export class AuthModule {}
```

**some.service.ts**

```
import { AuthHttp } from 'angular2-jwt';
...
getCompany(id: number) {
    return this.http.get(this._companyUrl + '/' + id)
        .map(res => res.json() || {},
                  err....);
}
```

**app.module.ts**

import {AuthModule} from "./services/auth.module";
...
@NgModule({
    providers: [
        AuthModule,
        ...
    ]
})

**If I do just that I obviously get:** `Unhandled Promise rejection: No provider for AuthHttp! ; Zone: angular ; Task: Promise.then ; Value:`

Does that mean I need to import AuthHttp into app.module.ts? If I do that then I'm not sure what progress has been made... I don't I get use AuthHttp in other modules... Does that make sense? 

Again, appreciate your help.

**Comment by sebhildebrandt** [comment]
If you e.g. have all services defined in a `core.module.ts`, then it is enough, just to import AuthModule there. This is actually the way I am doing it. 

... otherwise it should work importing YOUR `AuthModule` in all modules, where you define services.

**Comment by nicolassharp** [comment]
@sebhildebrandt but if I import `AuthModule` how do I pass the `AuthHttp` into the constructor of the service so I can use `authHttp`? `AuthModule` has no method `authHttp`.

**Comment by sebhildebrandt** [comment]
In the service, you don't import the AuthModule (see my example), there you import the AuthHttp from angular2-jwt. AuthModule only needs to be imported in one of your modules. 

Sebastian

**Comment by nicolassharp** [comment]
@sebhildebrandt and in `app.module.ts` do I import both `AuthModule` and `AuthHttp`? If I don't import AuthHttp in `app.module.ts` I can't import AuthHttp into my services... 

If there's a freelancer who wants to help me with this please get in touch!

**Comment by nicolassharp** [comment]
@sebhildebrandt would you mind please posting your `app.module.ts` file for your example above. Many thanks!

**Comment by nicolassharp** [comment]
@sebhildebrandt I got it working, thanks for your help! This is what I did:

**app.module.ts**

```
import { AuthHttp, AuthConfig} from 'angular2-jwt';
export function authHttpServiceFactory(http: Http, options: RequestOptions) {
  return new AuthHttp( new AuthConfig({}), http, options);
}

...

@NgModule({
    ...
   providers: [
       AuthService,
       AuthGuard,
       {
           provide: AuthHttp,
           useFactory: authHttpServiceFactory,
           deps: [ Http, RequestOptions ]
        }
    ]
})
```

**Comment by sebhildebrandt** [comment]
Glad to hear, that you solved it!

**Comment by CSchulz** [comment]
Are you using AoT?

**Comment by ansuman273** [comment]
This is not working with angular-cli 1.0.0 or Angular4
![err](https://cloud.githubusercontent.com/assets/4735068/25063081/fda6a112-21f7-11e7-8eeb-14cb529ee226.PNG)

Using all similar scopes @sebhildebrandt

**Comment by fahdsaeed** [comment]
I get this error 

ERROR in /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts (5,30): Cannot find module 'angular2-select'.
ERROR in Error: Error encountered resolving symbol values statically. Could not resolve angular2-select relative to /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts., resolving symbol DashboardModule in /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts, resolving symbol DashboardModule in /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/src/app/dashboard/dashboard.module.ts
    at Error (native)
    at syntaxError (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler/bundles/compiler.umd.js:25118:23)
    at StaticReflector.simplify (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler/bundles/compiler.umd.js:25130:13)
    at StaticReflector.annotations (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler/bundles/compiler.umd.js:24558:41)
    at _getNgModuleMetadata (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at /home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/kleidyaesara/public_html/aesara-knowledge-reservoir-client/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

webpack: Failed to compile.


Any help would be appreciated.
