### ISSUE TITLE
SystemJS js-base64 not found

### ISSUE THREAD

**Issue by danielserrao** [auth0/angular2-jwt#192]
Hey, I already had angular2-jwt installed and it was working well but for some reason I reinstalled the npm and it started to give this error. Then I installed the js-base64 manually with the command "npm i save-- @types/js-base64" and then the error changed to:

"(index):31 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3000/buffer ...
Error loading http://localhost:3000/buffer as "buffer" from http://localhost:3000/node_modules/js-base64/base64.js"

In this moment I have the following dependencies in my package.json:

`
    "@types/js-base64": "^2.1.4",
    "angular2-jwt": "^0.1.24",
    "js-base64": "^2.1.9",
`

Any idea of what is happenning?

Thanks for any help!

**Comment by danielserrao** [comment]
If I put "angular2-jwt": "0.1.19"  and reinstall the npm, there is another error:

"Error: (SystemJS) core_1.provide is not a function
	TypeError: core_1.provide is not a function
	    at Object.eval (http://localhost:3000/node_modules/angular2-jwt/angular2-jwt.js:206:12)"

**Comment by chenkie** [comment]
@danielserrao looking into this. For now you should be ok if you pin to v0.1.23.

**Comment by georgeedwards** [comment]
I too am facing this issue. I have tried with 0.1.22 and still seem to be getting the issue when I bundle my dependencies (with SystemJS Builder).

**Comment by bpblack** [comment]
I've been having issues with 0.1.24 as well. I was getting errors related to js-base64 that seemed to related to node_modules/buffer not existing, so I tried adding "buffer": "^5.0.0" in my package.json. This fixed the issues locally, but then I started having issues with a remote deploy where tokenNotExpired was throwing a no decode method for undefined exception. Pinning to v0.1.23 fixed that issue.

**Comment by svenlange** [comment]
We are also facing this problem in our build with 0.1.24

**Comment by andrzejpakula** [comment]
I have exactly the same problem, does anyone know the solution. Is JWT was raised to angular2 ?

node_modules/angular2-jwt/angular2-jwt.ts(1,24): error TS2307: Cannot find module 'js-base64'

**Comment by bonaparte89** [comment]
same problem here...
"angular2-jwt": "^0.1.24", and also with 0.1.23
"buffer": "^5.0.0",
"@types/js-base64": "^2.1.4",

`[11:50:10] Error on fetch for angular2-jwt at file:///C:/Users/user/Documents/WebProjects/Login/node_modules/angular2-jwt
        Loading dist\tmp\app\app.module.js
        Loading dist\tmp\app\main.js
        Error: EISDIR: illegal operation on a directory, read
    at Error (native)
[11:50:10] 'build.prod' errored after 15 s
[11:50:10] Error in plugin 'run-sequence(build.bundles.app)'
Message:
    Error on fetch for angular2-jwt at file:///C:/Users/user/Documents/WebProjects/Login/node_modules/angular2-jwt
        Loading dist\tmp\app\app.module.js
        Loading dist\tmp\app\main.js
        EISDIR: illegal operation on a directory, read
Details:
    originalErr: Error: EISDIR: illegal operation on a directory, read
Stack:
Error on fetch for angular2-jwt at file:///C:/Users/user/Documents/WebProjects/Login/node_modules/angular2-jwt
        Loading dist\tmp\app\app.module.js
        Loading dist\tmp\app\main.js
        Error: EISDIR: illegal operation on a directory, read
    at Error (native)`

**Comment by escardin** [comment]
@georgeedwards confirm the version npm installed and get back to us.
@bpblack My bad. I added the dep and ran unit tests, they ran okay and I didn't realise that the lib tries to use buffer if you're in a 'node' environment.

I tracked the issue down to SystemJS doesn't manage your transitive dependencies for you.

If you add the following to your SystemJS config in the map section:
```
      'js-base64':'npm:js-base64/base64.js',
      'buffer':'@empty'
```

If you're using the Angular CLI, I think you might need to also tell angular about js-base64. I haven't really used the CLI, and I'm a webpack user myself, so these sorts of things don't generally come up.

If something needs to be added elsewhere, please let me know so I can update the docs (I'm already going to update them for SystemJS).

**Comment by georgeedwards** [comment]
@escardin npm: 3.10.8

**Comment by escardin** [comment]
@georgeedwards Ah, I meant of angular2-jwt

**Comment by estradamarkie** [comment]
Facing the same issue on '0.1.23' or '0.1.24',

```
var map = { 
"angular2-jwt": "node_modules/angular2-jwt",
}

var package = { 
'angular2-jwt':            { main: './angular2-jwt.js', defaultExtension: 'js' },
}
```

**Comment by ashleymorris2** [comment]
I have had the same issue. 

@escardin fix has seemed to work.

**Comment by jayhuang75** [comment]
I'm using ionic2 RC, ionic serve seems fine. But goes with the ionic build, we have this error:
node_modules/angular2-jwt/angular2-jwt.ts:1:24: Cannot find module 'js-base64'.
Seems we have the same problem here. Any idea?

Thanks

**Comment by chenkie** [comment]
@jayhuang75 we're going to find a better way to handle this for SystemJS users. In the meantime you should be able to use v0.1.23 without error.

**Comment by karelwgonzalez** [comment]
I'm seeing this issue using also, and I'm using Webpack.

```
ERROR in [default] ../node_modules/angular2-jwt/angular2-jwt.ts:1:23 
Cannot find module 'js-base64'.
```

**Comment by jayhuang75** [comment]
@chenkie Thanks for the reply, I think we met last time in ng-conf. :) 
So I found the solution for this. Basically, dependencies we have to add the js-base64 and in devDependencies we have to add the @types/js-base64, then this error is not more there when we using ionic build. Hope this can help someone is updating their ionic2 app to RC.

Thanks

**Comment by karelwgonzalez** [comment]
@jayhuang75 Adding js-base64 to dependencies and @types/js-base64 to devDependencies also solved my issue in Webpack. Thanks for the tip!

**Comment by jayhuang75** [comment]
Happy to helping!

**Comment by chenkie** [comment]
@jayhuang75 that's right, we ate the food trucks! Hope to see you at ng-conf again in 2017 :)

**Comment by Bucabug** [comment]
@escardin wrote up the config required to fix this problem in the readme  https://github.com/auth0/angular2-jwt/commit/6b5816dc4f09f5603f7ea6ca9376c0650b80354b#diff-04c6e90faac2675aa89e2176d2eec7d8

Perhaps this thread can now be closed?

**Comment by dragonnblack** [comment]
@Bucabug Hi, I'm facing this problem too, but i'm using angular2 seed from mgechev ans there is not a systemjs.config then I don't know how to solve this.

Tried @karelwgonzalez astuce to add js-base64 and @types but doesn't work.

Any help please?

**Comment by iherbivore** [comment]
@dragonnblack I got the dev build working that way, but the production build is not. Were you able to get the production build working?

**Comment by dragonnblack** [comment]
@iherbivore when you launch like 'npm start --env dev' it's ok but not with 'npm star --env prod' ?
Which OS ?

**Comment by iherbivore** [comment]
Yeah the build.prod version... I can't get the mappings right. I think it
needs to go in the shims since it is a 3rd party dependency. But I think
that puts the `Base64` in the global scope already but the angular2-jwt is
trying to get `Base64` from `js-base64` and I can't get that mapped out
right. This is a lot of effort suddenly. I might need to try the other jwt
package.

**Comment by nottinhill** [comment]
Also see related: https://forum.ionicframework.com/t/rc0-library-dependency-export-jwt-angular2-js-base64/66644

**Comment by mc100s** [comment]
@dragonnblack I'm also using angular2 seed from mgechev but when I try to run the prod building, it tells me it can't fetch "_node_modules/js-base64.js_" (from "_angular2-jwt/angular2-jwt.js_").

Can you precise what you've done to solve your issue?

**Comment by dragonnblack** [comment]
@mc100s try to npm install --save js-base64 and buffer, that fixed for me

**Comment by estradamarkie** [comment]
for me this fixed the issue for systemJs config users.
I also installed js-base64 (npm install js-base64 --save-dev).
`var map = {

    "angular2-jwt": "node_modules/angular2-jwt",
    "js-base64": "node_modules/js-base64",
    'buffer':'@empty',
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {

    'angular2-jwt':            { main: './angular2-jwt.js', defaultExtension: 'js' },
    'js-base64':            { main: './base64.js', defaultExtension: 'js' },

  };`

**Comment by chenkie** [comment]
Solved by #201
