### PR TITLE
fix(JwtHelper) btoa does not support utf8 and escape is deprecated

### LINKED ISSUE #174: Method decodeToken has an error in charset
The method decodeToken decode the charset of the payload not correct. The key currencysymbol must be equal to '€'. (See snippet)

In Version 0.1.17 was everything ok with this method. After update to 0.1.22 or 0.1.23 we've got this problem.

Has everything changed in this method? Where is my error? :-)

Here a snippet of the payload with the error:
`{
"employeeid":2,
"subsidiaries":[
{
"currency":"EUR",
"currencysymbol":"â¬"
}
],
"exp":1474477088
}`

### PR DESCRIPTION
**Pull request by escardin**
I'm not especially comfortable with adding a new library dependency, as this one is 3kb minified, but I felt it was necessary to solve this properly.

I updated the test dependencies as they were broken when typings was missing.

Closes #174

### CODE REVIEW

**Comment by chenkie** [comment]
Thanks for taking the time to do this @escardin!

**Comment by chenkie** [comment]
I was testing this out before publishing and I'm seeing an error in a sample project that was working fine with v0.1.23. The sample uses TypeScript 1.8.

```
error TS1084: Invalid 'reference' directive syntax.
```

Looks like a TypeScript 2.0 issue. Does this PR introduce something that isn't backwards compatible?

**Comment by escardin** [comment]
I compiled it with the library tsc just fine. When I run my global 1.8 tsc, I get a ton of typings issues, but otherwise it's fine. I didn't see that particular error.

I did update dependencies. @types/es6-shim and reflect-metadata might be at issue?

Is the reference project public? I can't imagine it being a compile issue with this lib, but I haven't played much with ts2.

**Comment by chenkie** [comment]
This is the one I was trying it with https://github.com/auth0-samples/auth0-angularjs2-systemjs-sample/tree/master/01-Login

**Comment by escardin** [comment]
It was related to the ts2.0 merge. Remember that reference comment? it was complaining about that. ts1.8 didn't understand it.

I reworked the config file a bit and removed the typings for es6 shim, instead using the lib option (and I put it in the right place).

https://github.com/auth0/angular2-jwt/pull/177

**Comment by chenkie** [comment]
awesome thanks!
